<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU</Platforms>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <Description>Provides the native libvips shared library for Linux x64 .NET applications.</Description>
        <Version Condition="'$(BUILD_VERSION)' == ''">4.0.0</Version>
        <Version Condition="'$(BUILD_VERSION)' != ''">$(BUILD_VERSION)</Version>
        <AssemblyName>Soenneker.Libvips.Linux</AssemblyName>
        <PackageId>Soenneker.Libvips.Linux</PackageId>
        <PackageTags>libvips linux native binary image processing avif webp libvipslinux library csharp dotnet c# .net</PackageTags>
        <Copyright>Copyright © 2026 Jake Soenneker</Copyright>
        <Authors>Jake Soenneker</Authors>
        <Company>https://soenneker.com</Company>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <IsPackable>true</IsPackable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/soenneker/soenneker.libvips.linux</PackageProjectUrl>
        <RepositoryUrl>https://github.com/soenneker/soenneker.libvips.linux</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <RepositoryBranch>main</RepositoryBranch>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <LangVersion>latest</LangVersion>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
        <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
        <None Include="..\..\icon.png" Pack="true" PackagePath="\" />
        <None Include="Resources\linux-x64\libvips\lib\libvips.so.42" Condition="Exists('Resources\linux-x64\libvips\lib\libvips.so.42')" Pack="true" PackagePath="runtimes/linux-x64/native/" />
        <None Include="Resources\linux-x64\libvips\THIRD-PARTY-NOTICES.md" Condition="Exists('Resources\linux-x64\libvips\THIRD-PARTY-NOTICES.md')" Pack="true" PackagePath="" />
        <None Include="Resources\linux-x64\libvips\versions.json" Condition="Exists('Resources\linux-x64\libvips\versions.json')" Pack="true" PackagePath="" />
    </ItemGroup>
</Project>
